######## Set this as appropriate for the project. ########

filter:
    paths:
        - application/*
    dependency_paths:
        - application/vendor/*
    excluded_paths:
        - application/vendor/*
        - application/console/runtime/*

########### [End of project-specific section] ############

tools:
    php_cs_fixer:
        config: { level: psr2 }

build_failure_conditions:
    - 'elements.rating(<= F).exists' 
    - 'issues.label("bug").exists'
    - 'issues.label("security").exists'
    - 'issues.severity(>= CRITICAL).exists'
