version: "3"

services:
    app:
        build: .
        depends_on:
            - broker
            - brokerdb
        working_dir: /data
        environment:
            APP_ENV: test
            EMAIL_SERVICE_accessToken: dummy
            EMAIL_SERVICE_assertValidIp: "false"
            EMAIL_SERVICE_baseUrl: http://email
            EMAIL_SERVICE_validIpRanges: 192.168.0.0/16
            ID_BROKER_ADAPTER: fake
            ID_BROKER_CONFIG_accessToken: codeship-sync-to-broker-11111111
            ID_STORE_ADAPTER: fake
            IDP_NAME: Test

    broker:
        image: silintl/idp-id-broker:latest
        environment:
            APP_ENV: test
            API_ACCESS_KEYS: codeship-sync-to-broker-11111111
            EMAIL_SERVICE_accessToken: dummy
            EMAIL_SERVICE_assertValidIp: "false"
            EMAIL_SERVICE_baseUrl: http://email
            EMAIL_SERVICE_validIpRanges: 192.168.0.0/16
            EMAILER_CLASS: \Sil\SilIdBroker\Behat\Context\fakes\FakeEmailer
            IDP_NAME: local
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_HOST: brokerdb
            MYSQL_DATABASE: broker
            MYSQL_USER: broker
            MYSQL_PASSWORD: broker
            MFA_TOTP_apiBaseUrl: not_needed_here
            MFA_TOTP_apiKey: not_needed_here
            MFA_TOTP_apiSecret: not_needed_here
            MFA_WEBAUTHN_apiBaseUrl: not_needed_here
            MFA_WEBAUTHN_apiKey: not_needed_here
            MFA_WEBAUTHN_apiSecret: not_needed_here
        depends_on:
            - brokercron
            - brokerdb
        command: whenavail brokerdb 3306 60 ./run.sh

    brokercron:
        image: silintl/idp-id-broker:latest
        environment:
            API_ACCESS_KEYS: local-sync-123
            EMAIL_SERVICE_accessToken: dummy
            EMAIL_SERVICE_assertValidIp: "false"
            EMAIL_SERVICE_baseUrl: http://email
            EMAIL_SERVICE_validIpRanges: 10.20.40.0/24
            EMAILER_CLASS: \Sil\SilIdBroker\Behat\Context\fakes\FakeEmailer
            IDP_NAME: local
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_HOST: brokerdb
            MYSQL_DATABASE: broker
            MYSQL_USER: broker
            MYSQL_PASSWORD: broker
            MFA_TOTP_apiBaseUrl: not_needed_here
            MFA_TOTP_apiKey: not_needed_here
            MFA_TOTP_apiSecret: not_needed_here
            MFA_WEBAUTHN_apiBaseUrl: not_needed_here
            MFA_WEBAUTHN_apiKey: not_needed_here
            MFA_WEBAUTHN_apiSecret: not_needed_here
        depends_on:
            - brokerdb
        command: whenavail brokerdb 3306 60 ./run-cron.sh

    brokerdb:
        image: mariadb:10
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: broker
            MYSQL_USER: broker
            MYSQL_PASSWORD: broker
