services:
    app:
        build: .
        depends_on:
            - broker
            - brokerdb
        working_dir: /data
        environment:
            APP_ENV: test
            ID_BROKER_ADAPTER: fake
            ID_BROKER_CONFIG_accessToken: ci-sync-to-broker-11111111
            ID_STORE_ADAPTER: fake
            IDP_NAME: Test

    broker:
        image: ghcr.io/sil-org/idp-id-broker:latest
        environment:
            APP_ENV: test
            API_ACCESS_KEYS: ci-sync-to-broker-11111111
            EMAILER_CLASS: \Sil\SilIdBroker\Behat\Context\fakes\FakeEmailer
            IDP_NAME: local
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_HOST: brokerdb
            MYSQL_DATABASE: broker
            MYSQL_USER: broker
            MYSQL_PASSWORD: broker
            MFA_TOTP_apiBaseUrl: not_needed_here
            MFA_TOTP_apiKey: not_needed_here
            MFA_TOTP_apiSecret: not_needed_here
            MFA_WEBAUTHN_apiBaseUrl: not_needed_here
            MFA_WEBAUTHN_apiKey: not_needed_here
            MFA_WEBAUTHN_apiSecret: not_needed_here
        depends_on:
            brokercron:
                condition: service_started
            brokerdb:
                condition: service_healthy
        command: ./run.sh

    brokercron:
        image: ghcr.io/sil-org/idp-id-broker:latest
        environment:
            API_ACCESS_KEYS: local-sync-123
            EMAILER_CLASS: \Sil\SilIdBroker\Behat\Context\fakes\FakeEmailer
            IDP_NAME: local
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_HOST: brokerdb
            MYSQL_DATABASE: broker
            MYSQL_USER: broker
            MYSQL_PASSWORD: broker
            MFA_TOTP_apiBaseUrl: not_needed_here
            MFA_TOTP_apiKey: not_needed_here
            MFA_TOTP_apiSecret: not_needed_here
            MFA_WEBAUTHN_apiBaseUrl: not_needed_here
            MFA_WEBAUTHN_apiKey: not_needed_here
            MFA_WEBAUTHN_apiSecret: not_needed_here
        depends_on:
            - brokerdb
        command: ./run-cron.sh

    brokerdb:
        image: mariadb:10
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: broker
            MYSQL_USER: broker
            MYSQL_PASSWORD: broker
        healthcheck:
            test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
            start_period: 10s
            interval: 10s
            timeout: 5s
            retries: 3
