version: '2'
services:
    data:
        image: silintl/data-volume:latest
        volumes:
            - ./application:/data
        user: "${DOCKER_UIDGID}"

    db:
        image: silintl/mariadb:latest
        ports:
            - "3306"
        env_file:
            - ./local.env

    app:
        build: ./
        volumes_from:
            - data
        ports:
            - "8080:80"
        depends_on:
            - db
        env_file:
            - ./local.env

    cli:
        image: silintl/php7:latest
        volumes_from:
            - data
        working_dir: /data
        env_file:
            - ./local.env
        command: ["true"]

networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
            - subnet: 10.20.39.0/24
              gateway: 10.20.39.1

