version: '2'
services:
    data:
        image: silintl/data-volume:latest
        volumes:
            - ./application:/data
        user: "${DOCKER_UIDGID}"

    app:
        build: ./
        volumes_from:
            - data
        ports:
            - "8080:80"
        env_file:
            - ./local.env

    broker:
        image: silintl/idp-id-broker:develop
        environment:
            API_ACCESS_KEYS: local-sync-123
            IDP_NAME: local
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_HOST: brokerdb
            MYSQL_DATABASE: broker
            MYSQL_USER: broker
            MYSQL_PASSWORD: broker
        ports:
            - "8081:80"
        command: whenavail brokerdb 3306 60 ./run.sh

    brokerdb:
        image: silintl/mariadb:latest
        ports:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: broker
            MYSQL_USER: broker
            MYSQL_PASSWORD: broker

    cli:
        image: silintl/php7:latest
        volumes_from:
            - data
        working_dir: /data
        env_file:
            - ./local.env
        environment:
            ID_BROKER_CONFIG_accessToken: local-sync-123
        command: ["true"]
        ports: 
            - "22:22"

networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
            - subnet: 10.20.40.0/24
              gateway: 10.20.40.1

