version: '2'
services:
    data:
        image: silintl/data-volume:latest
        volumes:
            - ./application:/data
        user: "${DOCKER_UIDGID}"

    app:
        build: ./
        volumes_from:
            - data
        ports:
            - "8080:80"
        env_file:
            - ./local.env

    broker:
        image: silintl/idp-id-broker:develop
        env_file:
            - ./local.broker.env
        environment:
            API_ACCESS_KEYS: local-sync-123
            EMAIL_SERVICE_accessToken: dummy
            EMAIL_SERVICE_assertValidIp: "false"
            EMAIL_SERVICE_baseUrl: http://email
            EMAIL_SERVICE_validIpRanges: 10.20.40.0/24
            EMAIL_SIGNATURE: Dummy Signature for Local Development
            EMAILER_CLASS: \Sil\SilIdBroker\Behat\Context\fakes\FakeEmailer
            IDP_NAME: local
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_HOST: brokerdb
            MYSQL_DATABASE: broker
            MYSQL_USER: broker
            MYSQL_PASSWORD: broker
            PASSWORD_FORGOT_URL: https://www.example.com/forgot
            PASSWORD_PROFILE_URL: https://www.example.com/profile
            SUPPORT_EMAIL: support@example.com
        ports:
            - "8081:80"
        command: whenavail brokerdb 3306 60 ./run.sh
    
    brokercron:
        image: silintl/idp-id-broker:develop
        env_file:
            - ./local.broker.env
        environment:
            API_ACCESS_KEYS: local-sync-123
            EMAIL_SERVICE_accessToken: dummy
            EMAIL_SERVICE_assertValidIp: "false"
            EMAIL_SERVICE_baseUrl: http://email
            EMAIL_SERVICE_validIpRanges: 10.20.40.0/24
            EMAILER_CLASS: \Sil\SilIdBroker\Behat\Context\fakes\FakeEmailer
            IDP_NAME: local
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_HOST: brokerdb
            MYSQL_DATABASE: broker
            MYSQL_USER: broker
            MYSQL_PASSWORD: broker
        command: whenavail brokerdb 3306 60 ./run-cron.sh

    brokerdb:
        image: silintl/mariadb:latest
        ports:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: broker
            MYSQL_USER: broker
            MYSQL_PASSWORD: broker

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
        - "8001:80"
        depends_on:
        - brokerdb
        environment:
            PMA_HOST: brokerdb

    cli:
        build: ./
        volumes:
            - ${COMPOSER_CACHE_DIR}:/composer
        volumes_from:
            - data
        working_dir: /data
        env_file:
            - ./local.env
        environment:
            ID_BROKER_CONFIG_accessToken: local-sync-123
            ID_BROKER_CONFIG_assertValidIp: "false"
            COMPOSER_CACHE_DIR: /composer
        command: ["true"]
        ports: 
            - "22:22"

networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
            - subnet: 10.20.40.0/24
              gateway: 10.20.40.1

